### ISSUE TITLE
Binary extensions and -pedantic-errors

### ISSUE THREAD

**Issue by bevice** [mkleemann/cmake-avr#4]
With enabled `add_definitions("-pedantic-errors")`  avr-gcc causes an error in code that contains binary extensions, for example:

```
value = 0b10101; 
```

**Comment by mkleemann** [comment]
See http://gcc.gnu.org/onlinedocs/gcc-4.8.2/gcc/Alternate-Keywords.html#Alternate-Keywords for a detailed explanation. Adding __extension__ before the binary expression should solve this (not tested yet).
